In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)
from matplotlib import pyplot as plt
from decimal import Decimal
import math
from tqdm import tqdm

In [2]:
tqdm.pandas()
df = pd.read_csv('F:/公共交通/组合/subway_bus_20221103.csv')

C:\Users\孤怨\AppData\Local\Temp\ipykernel_3400\3816593045.py:2: DtypeWarning: Columns (1,10,13,14,15,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('F:/公共交通/组合/subway_bus_20221103.csv')

In [3]:
df['enstation_time'] = pd.to_datetime(df['enstation_time'])
df['card_no'] = df['card_no'].astype(np.float64)
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [4]:
df_group = df.groupby(by='card_no')
df_multiple = df_group.filter(lambda x : (len(x) >= 2))  #首尾都是公交车

In [5]:
df_multiple

,card_no,card_type,travel_type,enstation_code,enstation_name,lon1,lat1,enstation_time,exstation_code,exstation_name,lon2,lat2,exstation_time,line_no,line_name,busno,orientation,time_gap,arrive_time,rec_date
0,5.101001e+19,22,1,248.0,连山坡,104.242134,30.575626,2022-11-03 00:01:27,250.0,书房,104.212757,30.587580,2022-11-03 00:08:29,"2,2",NaN,NaN,1.0,NaN,NaN,20221103
1,5.101001e+19,22,1,664.0,万安,104.103418,30.483027,2022-11-03 00:00:57,665.0,麓山大道,104.099451,30.494865,2022-11-03 00:07:00,"6,6",NaN,NaN,1.0,NaN,NaN,20221103
2,5.101001e+19,22,1,251.0,龙平路,104.267966,30.560111,2022-11-03 00:08:55,252.0,龙泉驿,104.258988,30.572923,2022-11-03 00:13:14,"2,2",NaN,NaN,1.0,NaN,NaN,20221103
3,5.101001e+19,22,1,250.0,书房,104.267966,30.560111,2022-11-03 00:06:00,252.0,龙泉驿,104.242134,30.575626,2022-11-03 00:13:43,"2,2",NaN,NaN,1.0,NaN,NaN,20221103
4,5.101001e+19,22,1,250.0,书房,104.267966,30.560111,2022-11-03 00:05:15,252.0,龙泉驿,104.242134,30.575626,2022-11-03 00:13:23,"2,2",NaN,NaN,1.0,NaN,NaN,20221103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4462259,3.105170e+18,32,2,NaN,长益路西,104.027100,30.627150,2022-11-03 09:09:35,NaN,NaN,NaN,NaN,NaN,NaN,100,21037551.0,1.0,11.0,2022-11-03 09:09:34.000000000,20221103
4462263,3.105170e+18,32,2,NaN,蛟龙港海滨城,103.912300,30.602950,2022-11-03 16:09:33,NaN,NaN,NaN,NaN,NaN,NaN,368A,21038120.0,1.0,36.0,2022-11-03 16:10:19.000000000,20221103
4462264,6.222630e+18,20,2,NaN,南开为民学校北,104.269400,30.888430,2022-11-03 10:02:49,NaN,NaN,NaN,NaN,NaN,NaN,603,21157013.0,1.0,310.0,2022-11-03 09:57:49.000000000,20221103
4462265,6.222630e+18,20,2,NaN,长益路,104.030700,30.625530,2022-11-03 20:46:52,NaN,NaN,NaN,NaN,NaN,NaN,100,21037714.0,2.0,15.0,2022-11-03 20:46:47.000000000,20221103
4462266,6.230720e+18,20,2,NaN,地铁红牌楼站,104.030700,30.635380,2022-11-03 18:28:15,NaN,NaN,NaN,NaN,NaN,NaN,368A,21038903.0,1.0,23.0,2022-11-03 18:28:02.000000000,20221103

In [31]:
first_rows = df_multiple.drop_duplicates(subset='card_no',keep='first')

In [32]:
first_rows = first_rows[first_rows['travel_type'] == 2].sort_values('card_no')

In [33]:
last_rows = df_multiple.drop_duplicates(subset='card_no',keep='last')

In [34]:
last_rows = last_rows[last_rows['travel_type'] == 2].sort_values('card_no')

In [35]:
last_rows = last_rows[last_rows['card_no'].isin(first_rows['card_no'])]

In [39]:
first_rows = first_rows.reset_index(drop=True)

In [40]:
last_rows = last_rows.reset_index(drop=True)

In [43]:
last_rows['enstation_name_first'] = first_rows['enstation_name']
last_rows['lon1_first'] = first_rows['lon1']
last_rows['lat1_first'] = first_rows['lat1']

In [44]:
last_rows

,card_no,card_type,travel_type,enstation_code,enstation_name,lon1,lat1,enstation_time,exstation_code,exstation_name,lon2,lat2,exstation_time,line_no,line_name,busno,orientation,time_gap,arrive_time,rec_date,enstation_name_first,lon1_first,lat1_first
0,1.000000e+15,74,2,NaN,大天路东,104.0709,30.75871,2022-11-03 15:12:52,NaN,NaN,NaN,NaN,NaN,NaN,K15,21046321.0,2.0,16.0,2022-11-03 15:12:46.000000000,20221103,先驱大道路口,104.067700,30.758740
1,1.000000e+15,69,2,NaN,民兴路中,104.1456,30.68870,2022-11-03 17:46:54,NaN,NaN,NaN,NaN,NaN,NaN,14,21017819.0,2.0,36.0,2022-11-03 17:46:28.000000000,20221103,民兴北一路中,104.157911,30.686599
2,1.000000e+15,69,2,NaN,吉瑞三路,104.0581,30.55589,2022-11-03 16:14:52,NaN,NaN,NaN,NaN,NaN,NaN,240,21038566.0,1.0,36.0,2022-11-03 16:15:38.000000000,20221103,中和二街康和路口,104.100800,30.547170
3,1.000000e+15,69,2,NaN,塔子山公园,104.1200,30.63862,2022-11-03 12:44:12,NaN,NaN,NaN,NaN,NaN,NaN,K6,21017839.0,1.0,122.0,2022-11-03 12:46:24.000000000,20221103,鲸龙路龙工南路口,104.255600,30.541240
4,1.000000e+15,69,2,NaN,火车北站东,104.0784,30.69466,2022-11-03 15:13:14,NaN,NaN,NaN,NaN,NaN,NaN,55,21038596.0,1.0,20.0,2022-11-03 15:13:44.000000000,20221103,东林二路口,104.127100,30.715550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305010,3.105170e+18,32,2,NaN,凤凰北大街中,103.8915,30.68874,2022-11-03 17:06:15,NaN,NaN,NaN,NaN,NaN,NaN,772,21143280.0,1.0,11.0,2022-11-03 17:06:14.000000000,20221103,长安路中,103.852700,30.699350
305011,3.105170e+18,32,2,NaN,地铁省骨科医院站,104.0410,30.65102,2022-11-03 15:15:12,NaN,NaN,NaN,NaN,NaN,NaN,115,21022273.0,1.0,46.0,2022-11-03 15:16:08.000000000,20221103,芳草东街口,104.058000,30.625020
305012,3.105170e+18,32,2,NaN,吉泰路天府三街口,104.0643,30.54648,2022-11-03 14:27:17,NaN,NaN,NaN,NaN,NaN,NaN,512,21074265.0,1.0,4.0,2022-11-03 14:27:23.000000000,20221103,惠王陵西路口,104.144000,30.616320
305013,3.105170e+18,32,2,NaN,黄土村公交站,103.9636,30.68593,2022-11-03 17:40:44,NaN,NaN,NaN,NaN,NaN,NaN,229,21022020.0,1.0,65.0,2022-11-03 17:41:59.000000000,20221103,成飞大道日月大道口,103.961095,30.678466
305014,3.105170e+18,32,2,NaN,建设南新路南,104.1056,30.66396,2022-11-03 17:28:00,NaN,NaN,NaN,NaN,NaN,NaN,71,21042108.0,1.0,14.0,2022-11-03 17:27:56.000000000,20221103,双林北支路东,104.114200,30.657310

In [ ]:
def in2F_need3(Dataframe_1,Dataframe_2):
    out = []
    lon1 = Dataframe_1['lon1_first']
    lat1 = Dataframe_1['lat1_first']
    line_name = Dataframe_1['line_name_previous']
    orientation = Dataframe_1['orientation_previous']
    try:
        bus_line_rule = (Dataframe_2['line_name'] == line_name) & \
                        (Dataframe_2['orientation'] == orientation)
        use_bus = Dataframe_2[bus_line_rule]
        use_bus['dis'] = use_bus.apply(haversine_distance, args=[lon1, lat1], axis=1)
        min_index = use_bus['dis'].idxmin()
        min_row = use_bus.loc[min_index]
        out.extend([min_row['gcj02_lng'],min_row['gcj02_lat'],min_row['stop_name']])
        return out
    except:
        out.extend(['NaN','NaN',999])
        return out
        print('可排除误差')

In [ ]:
df_multiple.sort_values(['card_no','enstation_time'],inplace=True)
df_multiple.reset_index(inplace=True,drop=True)

In [ ]:
df_multiple['travel_type_previous'] = df_multiple['travel_type'].shift(1)
df_multiple['line_name_previous'] = df_multiple['line_name'].shift(1)
df_multiple['orientation_previous'] = df_multiple['orientation'].shift(1)
df_multiple['enstation_code_previous'] = df_multiple['enstation_code'].shift(1)
df_multiple['enstation_name_previous'] = df_multiple['enstation_name'].shift(1)
df_multiple['lon1_previous'] = df_multiple['lon1'].shift(1)
df_multiple['lat1_previous'] = df_multiple['lat1'].shift(1)
df_multiple['enstation_time_previous'] = df_multiple['enstation_time'].shift(1)
df_multiple['card_no_previous'] = df_multiple['card_no'].shift(1)

In [ ]:
df_multiple

In [ ]:
df_multiple = df_multiple[((df_multiple['travel_type'] == 2) | 
                           (df_multiple['travel_type_previous'] == 2)) & 
                            (df_multiple['card_no'] == df_multiple['card_no_previous'])] #取出能匹配站点的数据

In [ ]:
df_multiple

In [ ]:
df_multiple['time_dif'] = abs((df_multiple['enstation_time_previous'] - df_multiple['enstation_time']).dt.total_seconds())

In [ ]:
time_rule = (df_multiple['time_dif'] <= 7200) | (df_multiple['time_dif'] >=28800)

In [ ]:
df_multiple = df_multiple[time_rule]

In [ ]:
df_multiple.reset_index(inplace=True,drop=True)

In [ ]:
df_multiple

In [45]:
def in2F(Dataframe_1,Dataframe_2):
    out = []
    lon1 = Dataframe_1['lon1']
    lat1 = Dataframe_1['lat1']
    line_name = Dataframe_1['line_name_previous']
    orientation = Dataframe_1['orientation_previous']
    try:
        bus_line_rule = (Dataframe_2['line_name'] == line_name) & \
                        (Dataframe_2['orientation'] == orientation)
        use_bus = Dataframe_2[bus_line_rule]
        use_bus['dis'] = use_bus.apply(haversine_distance, args=[lon1, lat1], axis=1)
        min_index = use_bus['dis'].idxmin()
        min_row = use_bus.loc[min_index]
        out.append(min_row['gcj02_lng'])
        out.append(min_row['gcj02_lat'])
        out.append(min_row['stop_name'])
        return out
    except:
        return out
        print('可排除误差')

def haversine_distance(Dataframe, lon2, lat2):
    import math
    R = 6371
    dLon = math.radians(lon2 - Dataframe['gcj02_lng'])
    dLat = math.radians(lat2 - Dataframe['gcj02_lat'])
    lat1 = math.radians(Dataframe['gcj02_lat'])
    lat2 = math.radians(lat2)
    a = math.sin(dLat / 2) ** 2 + \
        math.sin(dLon / 2) ** 2 * math.cos(lat1) * math.cos(lat2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    dis = R * c
    return dis

In [12]:
df_bus = pd.read_csv('test/chengdu_busstation_gaodev2.csv')

In [13]:
df_multiple = df_multiple[df_multiple['travel_type_previous'] == 2]

In [35]:
df_test = df_multiple[:10]

In [37]:
test_out = df_multiple[:10].apply(in2F,args=[df_bus],axis=1)

In [16]:
test_out.reset_index(inplace=True,drop=True)

In [38]:
test_out

11195       [104.103172, 30.70517941, 昭觉寺公交站]
11196        [103.9977835, 30.59664263, 文昌路北]
11200      [104.1644814, 30.59312288, 洪柳花园二期]
11205    [104.0393659, 30.70135569, 一品天下长庆路口]
11206      [103.9622946, 30.66324538, 万家湾公交站]
11208     [104.0119155, 30.67307334, 金沙公交枢纽站]
11211      [104.0687809, 30.57259955, 高新区孵化园]
11212     [104.0585531, 30.643838, 浆洗街(华西医院)]
11213        [104.0345838, 30.63236456, 红牌楼东]
11214      [104.0435436, 30.63718565, 高升桥东路北]
dtype: object

In [39]:
df_test['exstation_name_previous'] = test_out.apply(lambda x:x[2])
df_test['lon2_previous'] = test_out.apply(lambda x:x[0])
df_test['lat2_previous'] = test_out.apply(lambda x:x[1])

C:\Users\孤怨\AppData\Local\Temp\ipykernel_13160\2952493432.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['exstation_name_previous'] = test_out.apply(lambda x:x[2])
C:\Users\孤怨\AppData\Local\Temp\ipykernel_13160\2952493432.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['lon2_previous'] = test_out.apply(lambda x:x[0])
C:\Users\孤怨\AppData\Local\Temp\ipykernel_13160\2952493432.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['lat2_previous'] = test_out.apply(lambda x:x[1])

In [40]:
df_test

,card_no,card_type,travel_type,enstation_code,enstation_name,lon1,lat1,enstation_time,exstation_code,exstation_name,lon2,lat2,exstation_time,line_no,line_name,busno,orientation,time_gap,arrive_time,rec_date,seq,travel_type_next,enstation_name_next,travel_type_previous,line_name_previous,orientation_previous,enstation_code_previous,enstation_name_previous,lon1_previous,lat1_previous,enstation_time_previous,exstation_name_previous,lon2_previous,lat2_previous
11195,5.096991e+15,21,1,314.0,钟楼,108.947068,34.261023,2022-11-04 07:16:36,561.0,回龙,104.011886,30.444594,2022-11-04 08:51:49,"3,5",NaN,NaN,1.0,NaN,NaN,20221104,1,1.0,回龙,2.0,1,2.0,NaN,佳灵路,104.027435,30.633048,2022-11-04 08:25:09,昭觉寺公交站,104.103172,30.705179
11196,5.096991e+15,21,1,561.0,回龙,104.011886,30.444594,2022-11-04 15:39:34,314.0,钟楼,108.947068,34.261023,2022-11-04 17:24:48,"5,3",NaN,NaN,2.0,NaN,NaN,20221104,2,1.0,海昌路,2.0,57,1.0,NaN,武侯祠(锦里),104.049203,30.644384,2022-11-04 18:34:23,文昌路北,103.997783,30.596643
11200,5.097003e+15,69,2,NaN,地铁蜀新大道站,103.902757,30.791391,2022-11-04 20:02:55,NaN,NaN,NaN,NaN,NaN,NaN,P08,21128918.0,2.0,397.0,2022-11-04 19:56:28.000000000,20221104,3,1.0,龙泉驿,2.0,891,2.0,NaN,北大成都附属实验学校,104.185600,30.573240,2022-11-04 08:01:41,洪柳花园二期,104.164481,30.593123
11205,5.097013e+15,21,1,251.0,龙平路,104.258988,30.572923,2022-11-04 15:09:45,1722.0,黄石,103.813977,30.721646,2022-11-04 16:54:21,"2,1",NaN,NaN,1.0,NaN,NaN,20221104,1,1.0,黄石,2.0,215,1.0,NaN,瑞星路口,103.994021,30.663431,2022-11-04 08:31:13,一品天下长庆路口,104.039366,30.701356
11206,5.097013e+15,21,1,1722.0,黄石,103.813977,30.721646,2022-11-04 19:42:33,250.0,书房,104.242134,30.575626,2022-11-04 21:19:51,"1,2",NaN,NaN,2.0,NaN,NaN,20221104,2,1.0,书房,2.0,37,2.0,NaN,东坡大道中,103.997479,30.661359,2022-11-04 08:36:09,万家湾公交站,103.962295,30.663245
11208,5.097013e+15,21,1,434.0,玉双路,104.099315,30.653452,2022-11-04 21:52:02,725.0,二仙桥,104.126360,30.680880,2022-11-04 22:11:12,"4,7",NaN,NaN,1.0,NaN,NaN,20221104,2,1.0,金星,2.0,309,1.0,NaN,地铁文化宫站,104.009093,30.670635,2022-11-04 18:30:29,金沙公交枢纽站,104.011916,30.673073
11211,5.097042e+15,69,2,NaN,科干校,104.186500,30.584620,2022-11-04 18:19:29,NaN,NaN,NaN,NaN,NaN,NaN,891,21119557.0,2.0,462.0,2022-11-04 18:27:21.000000000,20221104,1,2.0,科干校,2.0,125,2.0,NaN,益州大道府城大道口,104.060237,30.589335,2022-11-04 14:06:08,高新区孵化园,104.068781,30.572600
11212,5.097042e+15,69,2,NaN,科干校,104.186500,30.584620,2022-11-04 18:19:50,NaN,NaN,NaN,NaN,NaN,NaN,891,21119557.0,2.0,441.0,2022-11-04 18:27:21.000000000,20221104,2,1.0,双桥路,2.0,340,2.0,NaN,美洲花园,104.038600,30.600866,2022-11-04 15:33:22,浆洗街(华西医院),104.058553,30.643838
11213,5.097073e+15,21,1,824.0,杉板桥,104.119292,30.664170,2022-11-04 13:30:00,245.0,洪河,104.157510,30.605015,2022-11-04 13:55:02,"8,2",NaN,NaN,2.0,NaN,NaN,20221104,1,1.0,洪河,2.0,248,2.0,NaN,地铁武青南路站,103.984326,30.622979,2022-11-04 08:52:01,红牌楼东,104.034584,30.632365
11214,5.097073e+15,21,1,245.0,洪河,104.157510,30.605015,2022-11-04 22:47:38,824.0,杉板桥,104.119292,30.664170,2022-11-04 23:12:24,"2,8",NaN,NaN,1.0,NaN,NaN,20221104,2,1.0,红高路,2.0,242,1.0,NaN,业兴北路南,103.964846,30.630660,2022-11-04 17:20:39,高升桥东路北,104.043544,30.637186